#!/usr/bin/env bash

# Environment Flags
set -o errexit  # Exit when a command fails
set -o pipefail # Catch mysqldump fails
set -o nounset  # Exit when using undeclared variables

FOLDER="$(readlink -f "${BASH_SOURCE[0]}" | xargs dirname)"

if [[ "${1:-}" == "chrome-extension-path" ]]; then
  echo "${FOLDER}/submodules/browser-tools-mcp/chrome-extension"
  exit 0
fi

cd "${FOLDER}" || exit 1

(
  cd "./submodules/browser-tools-mcp/browser-tools-server" || exit 1
  if [[ ! -d "./node_modules" ]]; then
    npm install >/dev/null
  fi
)

(
  cd "./submodules/browser-tools-mcp/browser-tools-mcp" || exit 1
  if [[ ! -d "node_modules" ]]; then
    npm install >/dev/null
  fi
)

(
  cd "./submodules/browser-tools-mcp/browser-tools-server" || exit 1
  npm start >/dev/null
) &

sleep 2s || sleep 2

(
  cd "./submodules/browser-tools-mcp/browser-tools-mcp" || exit 1
  npm start
)
